[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[rpc_endpoints]
bsc_testnet = "${BSC_TESTNET_RPC_URL}"

[etherscan]
bsc_testnet = { key = "${BSCSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config